[defaults]
suppress = true
emergency_stop = "ctrl shift e"
program = ["*mpv*", "*celluloid*"]  # either front-end; Celluloid's window class has no "mpv" in it


# k: pause
[binds.k]
bind = "space"


# '<' / '>': playback slow-down/speed-up
[binds."rshift >"]
bind = "]"

[binds."rshift <"]
bind = "["


# playback halfing/doubling (no, youtube doesn't distinguish between SHIFTS, but I think it makes sense)
# Distinct from the above shift-bind pair. If you comment this out, both 'shift's would serve the above pair!
[binds."shift >"]
bind = "shift ]"

[binds."shift <"]
bind = "shift ["


# fullscreen already uses 'f' for both


# youtube's captions = celluloid's subtitles
# (just does activation/deactivation, if any; cycling not included... it's "j" on `mpv`, and youtube hadn't implement that)
[binds.c]
bind = "v"


# up / down: app volume-up/down
[binds.up]
bind = "0"

[binds.down]
bind = "9"


# next / prev
[binds."shift N"]
bind = "shift >"

[binds."shift P"]
bind = "shift <"


